@startuml
class FinalBossEnemy {
    + FinalBossEnemy(content:ContentManager, startPosition:Vector2, movementSpeed:float)
    + <<override>> Update(gameTime:GameTime, playerPosition:Vector2) : void
    + <<override>> Attack(gameTime:GameTime, playerPosition:Vector2) : void
}
Enemy <|-- FinalBossEnemy
@enduml
